--ALTER TABLE


--ALTERAÇÃO DAS CARACTERISTICAS DOS CAMPOS DE UMA TABELA
--UTILIZADO PARA ADICIONAR, DELETAR OU MODIFICAR COLUNAS DE UMA TABELA EXISTENTE.
------------------------------------------------------------------------------------------

SELECT *
INTO TEMP --CRIANDO UMA TABELA COM TODAS AS INFORMAÇÕES DA TABELA ALUNO.
FROM ALUNOS;

EXEC SP_COLUMNS TEMP; --VERIFICANDO TODAS AS COLUNAS DA TABELA QUE FOI CRIADA.
------------------------------------------------------------------------------------------

--ADICIONAR COLUNA

SELECT *
FROM TEMP;

ALTER TABLE TEMP
	ADD CPF NUMERIC(11); --ADICIONANDO UMA COLUNA NA TABELA TEMP COM O NOME DE CPF.

SELECT *
FROM TEMP; --VERIFICANDO SE REALMENTE FOI CRIADO ESSA COLUNA

UPDATE TEMP	--MOSTRANDO PARA O SISTEMA QUE VAI TER UMA ATUALIZAÇÃO DE DADOS DENTRO DA TABELA
SET CPF = 1112223334 --SENDO QUE A COLUNA QUE VAI RECEBER É A COLUNA CPF
WHERE id_aluno = 1; --E QUE O ALUNO COM ID 1 QUE VAI RECEBER ESSA INFORMAÇÃO.

ALTER TABLE TEMP --ALTERANDO NOVAMENTE A TABELA TEMP
 ADD EMAIL VARCHAR(100); --ADICIONANDO MAIS UMA COLUNA, AGORA COM O NOME EMAIL

SELECT *
FROM TEMP;--VERIFICANDO SE REALMENTE A COLUNA FOI CRIADA
------------------------------------------------------------------------------------------

--APAGAR COLUNA
ALTER TABLE TEMP --ALTERANDO A TABELA TEMP
	DROP COLUMN EMAIL; --EXCLUINDO A COLUNA EMAIL.

SELECT *
FROM TEMP; --VERIFICANDO SE O COMANDO DEU CERTO
------------------------------------------------------------------------------------------

--ALTERAR TIPO DE DADOS DE UMA COLUNA

ALTER TABLE TEMP --ALTERANDO A TABELA TEMP
	DROP COLUMN CPF; --DELETANDO A COLUNA CPF.

ALTER TABLE TEMP --ALTERANDO A TABELA TEMP
	ADD CPF VARCHAR(100); --ACRESCENTANDO A COLUNA CPF, AGORA EM VARCHAR.

EXEC SP_COLUMNS TEMP; --TIRANDO A LIMPO PARA VER SE A COLUNA FOI REGISTRADA DE FORMA CERTA

ALTER TABLE TEMP --ALTERANDO NOVAMENTE A TABELA TEMP
	ALTER COLUMN CPF NUMERIC (11); --MODIFICANDO A COLUNA CPF PARA NUMERIC, ANTES ERA VARCHAR.

--ENTAO SE FOR PRECISO ALTERAR UMA COLUNA, BASICAMENTE BASTA DAR UM ALTER TABLE, E MODIFICAR DE FORMA DESEJADA.

DROP TABLE TEMP; --APAGANDO A TABELA.
