--TRANSACTION


--BEGIN TRANSACTION
--ROLLBACK TRANSACTION
--COMMIT;
------------------------------------------------------------------------------------------

SELECT *
INTO TEMP
FROM ALUNOS;

SELECT *
FROM TEMP;

/*BEGIN TRAN, OU BEGIN TRANSACTION, SERA BASICAMENTE UMA ZONA NEUTRA, UMA ZONA DE TESTE
NELA VOCE PODE FAZER AS ALTERAÇÕES, ATUALIZAÇÕES, DELETES, TUDO O QUE QUISER DENTRO DE UMA TABELA
SEM QUE ESSA TABELA SOFRA ESSA ALTERAÇÕES.
O QUE VAI DETERMINAR SE ESSAS ALTERAÇÕES VÃO SER DEFINIDAS, VAI SER O COMANDO FINAL.

NA QUESTÃO DE DEFINIR AS ALTERAÇÕES, NO FINAL DA TRANSACTION, BASTA VOCE DAR UM COMMIT, O
COMMIT SERA O AVAL PARA FINALIZAR E ACRESCENTAR ESSAS ALTERAÇÕES. TUDO O QUE FOI FEITO ANTES
DO COMMIT, SERA VALIDADO DENTRO DA TABELA.

AGORA CASO VOCE TENHA FEITO O SCRIPT DE FORMA INCORRETA, OU ALGO APRESENTOU ERRO, BASTA DAR UM 
ROLLBACK NO FINAL DA SUA TRANSAÇÃO, QUE ASSIM ELA NAO FARA A ALTERAÇÃO E AS INFORMAÇÕES DA TABELA
NÃO SOFRERAM NADA.
*/

------------------------------------------------------------------------------------------
BEGIN TRAN;
    UPDATE TEMP
		SET SEXO = LOWER(SEXO); --NESSE CASO, COM O COMMIT NO FINAL, A ALTERAÇÃO DA TABELA FOI CONCLUIDA
COMMIT;

BEGIN TRAN 
	UPDATE TEMP
	SET SEXO = UPPER(SEXO); --NESSE CASO, COM O ROLLBACK, A ALTERAÇÃO NÃO FOI CONCLUIDA.
ROLLBACK;

--ENTAO BASICAMENTE O BEGIN SERVE BEM PARA PROTEGER OS DADOS DENTRO DE UMA TABELA.
--AINDA MAIS QUANDO ESSA TABELA TEM MUITA INFORMAÇÃO, PARA QUE NÃO SOFRA NENHUM TIPO DE ALTERAÇÃO INDESEJADA.

DROP TABLE TEMP;