--CASE -- ALTERAR FORMA DE VISUALIZAÇÃO DE DADOS
--ELSE --SENAO
--END  --FINALIZAR
-------------------------------------------------------------------------------------------------------------------------------------------------

--BASICAMENTE NA QUERY ABAIXO, ESTAMOS PEDINDO PARA QUE O SISTEMA USE TODAS AS INFORMAÇÕES DA QUERY Y
--PARA CRIAR UMA TABELA TTEMP.
--ENTAO NO CASO O X.* QUER DIZER QUE ELE VAI USAR TUDO O QUE ESTA NESSA QUERY PARA CRIAR UMA TABELA ESPECIFICA COM TODOS OS CAMPOS CITADOS.

SELECT X.*													--CRIANDO UMA TABELA
INTO TTEMP													--COM O NOME TTEMP	
FROM (														--COPIE TODAS AS COLUNAS DA SUBQUERY		
		SELECT ROW_NUMBER() OVER(ORDER BY ID_ALUNO) LINHA,	--FAÇA UMA COLUNA NOVA CHAMADA LINHA, AONDE ELA ORDENE AS LINHAS DE TODAS AS COLUNAS
			   Y.ID_ALUNO									--MOSTRE O ID DO ALUNO
			  ,Y.NOME										--NOME DO ALUNO
			  ,Y.SEXO                                       --SEXO DO ALUNO
			  ,Y.NOME_CURSO									--NOME DO CURSO
			  ,Y.DATA_INICIO								--DATA INICIO DO CURSO
			  ,Y.DATA_TERMINO								--DATA TERMINO
	    FROM (												--CRIAÇÃO DA SUBQUERY
	    SELECT A.ID_ALUNO									--MOSTRE O ID ALUNO
			  ,A.NOME										--NOME DO ALUNO
			  ,A.SEXO                                       --SEXO DO ALUNO
			  ,C.NOME_CURSO									--NOME DO CURSO
			  ,T.DATA_INICIO								--DATA INICIO CURSO
			  ,T.DATA_TERMINO								--DATA TERMINO CURSO
		FROM ALUNOSXTURMAS AT								--PEGUE ESSAS INFORMAÇÕES DA TABELA ALUNOSXTURMA
				INNER JOIN TURMAS T							--FAÇA UMA RELAÇÃO COM A TABELA TURMA
					ON (T.ID_TURMA = AT.ID_TURMA)			--ONDE O ID TURMA DA TABELA TURMA É IGUAL A ID TURMA DA TABELA ALUNOSXTURMAS	
					INNER JOIN CURSOS C						--FAÇA UMA RELAÇÃO COM A TABELA CURSO
						ON (C.ID_CURSO = T.ID_CURSO)		--ONDE O ID CURSO DA TABELA CURSO É IGUAL A ID CURSO DA TABELA TURMA	
						INNER JOIN ALUNOS A					--FAÇA UMA RELAÇÃO COM A TABELA ALUNOS	
							ON (A.ID_ALUNO = AT.ID_ALUNO)	--ONDE O ID ALUNO DA TABELA ALUNO É IGUAL A ID ALUNO DA TABELA ALUNOSXTURMAS
			 ) Y											--FECHE A SUBQUERY
	 )X														--FECHE A QUERY PRINCIPAL
-------------------------------------------------------------------------------------------------------------------------------------------------

--QUERY 1 - TRAZER NOME, SEXO E NOME DO CURSO, MUDANDO ALGUMAS CARACTERISTICAS NO SEXO COM CASE

SELECT NOME,							--SELECIONE O NOME
	   CASE SEXO						--ENCONTRE A COLUNA SEXO
			WHEN 'M' THEN 'MASCULINMO'	--E ALTERE PRA MASCULINO QUANDO FOR M
			WHEN 'F' THEN 'FEMININO'	--E ALTERE PRA FEMININO QUANDO FOR F
	   ELSE 'VERIFIQUE' END as SEXO,	--SENAO DIGITE VERIFIQUE, FINALIZE O SISTEM E ALIAS SEXO
	   NOME_CURSO						--SELECIONE O NOME DO CURSO
FROM TTEMP;								--DA TABELA TTEMP.
-------------------------------------------------------------------------------------------------------------------------------------------------

--QUERY 2 - TRAZER NOME, SEXO, E NOME DO CURSO, MUNDANDO ALGUMAS CARACTERISTICAS NO SEXO E NO NOME DO CURSO USANDO CASE.

SELECT NOME,										--SELECIONE O NOME
	   CASE SEXO									--SELECIONE O SEXO
	   	 	WHEN 'M' THEN 'MASCULINO'				--E ALTERE PRA MASCULINO QUANDO FOR M
			WHEN 'F' THEN 'FEMININO'				--E ALTERE PRA FEMININO QUANDO FOR F
	   ELSE 'VERIFIQUE'								--SENAO DIGITE VERIFIQUE	
	   END AS SEXO,									--FINALIZE COM ALIAS SEXO
			CASE NOME_CURSO							--SELECIONE A COLUNA NOME_CURSO
				WHEN 'Word Avançado' THEN 'WORDZAO'	--E ALTERE PARA WORDZAO QUANDO FOR WORD AVANÇADO
			ELSE 'OUTRO CURSO'						--SENAO VERIFIQUE
			END AS "NORME DO CURSO"					--FINALIZE COM ALIAS NOME DO CURSO	
FROM TTEMP;											--DA TABELA TTEMP.
-------------------------------------------------------------------------------------------------------------------------------------------------

--QUERY 3 QUERY 2 - TRAZER NOME, SEXO, E NOME DO CURSO, MUNDANDO ALGUMAS CARACTERISTICAS NO SEXO E NO NOME DO CURSO USANDO CASE.
--USANDO TAMBEM DISTINCT

SELECT DISTINCT NOME,								--SELECIONE O NOME
	   CASE SEXO									--SELECIONE O SEXO
	   	 	WHEN 'M' THEN 'MASCULINO'				--E ALTERE PRA MASCULINO QUANDO FOR M
			WHEN 'F' THEN 'FEMININO'				--E ALTERE PRA FEMININO QUANDO FOR F
	   ELSE 'VERIFIQUE'								--SENAO DIGITE VERIFIQUE	
	   END AS SEXO,									--FINALIZE COM ALIAS SEXO
			CASE NOME_CURSO							--SELECIONE A COLUNA NOME_CURSO
				WHEN 'Word Avançado' THEN 'WORDZAO'	--E ALTERE PARA WORDZAO QUANDO FOR WORD AVANÇADO
			ELSE 'OUTRO CURSO'						--SENAO VERIFIQUE
			END AS "NORME DO CURSO"					--FINALIZE COM ALIAS NOME DO CURSO	
FROM TTEMP;											--DA TABELA TTEMP.
-------------------------------------------------------------------------------------------------------------------------------------------------

--VERIFICAR SE TEM ALGUM ERRO COM O SEXO

SELECT X.*												--SELECIONE DA MINHA TABELA	
	FROM (												--TODA A QUERY A BAIXO
				SELECT  ID_ALUNO,						--SELECIONE O ID DO ALUNO
						NOME,							--SELECIONE O NOME
						CASE SEXO						--ENCONTRE A COLUNA SEXO
							WHEN 'M' THEN 'MASCULINMO'	--E ALTERE PRA MASCULINO QUANDO FOR M
							WHEN 'F' THEN 'FEMININO'	--E ALTERE PRA FEMININO QUANDO FOR F
					   ELSE 'VERIFIQUE' END as SEXO,	--SENAO DIGITE VERIFIQUE, FINALIZE O SISTEM E ALIAS SEXO
					   NOME_CURSO						--SELECIONE O NOME DO CURSO
				FROM TTEMP								--DA TABELA TTEMP.
		  )X											--FECHANDO SUBQUERY
WHERE SEXO = 'VERIFIQUE'								--SOMENTE QUANDO O SEXO FOR IGUAL A VERIFIQUE
-------------------------------------------------------------------------------------------------------------------------------------------------

SELECT NOME											--SELECIONE NOME DO ALUNO	
	  ,NOME_CURSO									--SELECIONE NOME DO CURSO
	  ,CONVERT(DATE, DATA_INICIO) AS "DATA INICIO",	--CONVERTA A DATA INICIO PARA DATE E DE UM ALIAS DATA INICIO
		CASE YEAR(DATA_INICIO)						--DENTRO DA COLUNA DATA INICIO PROCURE O ANO E FAÇA	
			WHEN 2019 THEN 'ANO ANTERIOR'			--CASO ENCONTRE O ANO DE 2019 MOSTRE O RESULTADO DE ANO INTERIOR
			WHEN 2020 THEN 'ANO ATUAL'				--CASO ENCONTRE O ANO DE 2020 MOSTRE O RESULTADO DE ANO ATUAL
			WHEN 2021 THEN 'PROXIMO ANO'			--CASO ENCONTRE O ANO DE 2021 MOSTRE O RESULTADO DE PROXIMO ANO
		ELSE 'ANO INVALIDO'							--SENAO MOSTRE O RESULTADO DE ANO INVALIDO
		END AS "ANALISE DE ANO"						--FINALIZE COLOCANDO O RESULTADO EM UMA COLUNAD E ALIAS 'ANALISE DE ANO'
FROM TTEMP;											--PEGUE AS INFORMAÇÕES DA TABELA TTEMP.
-------------------------------------------------------------------------------------------------------------------------------------------------

--TESTANDO QUERY 1
SELECT NOME,
		CASE SEXO
			WHEN 'F' THEN 'FEMININO'
			WHEN 'M' THEN 'MASCULINO'
		ELSE 'VERIFIQUE'
		END AS "SEXO DO ALUNO",

				CASE NOME_CURSO
					WHEN 'WORD AVANÇADO' THEN 'WORDZÃO'
				ELSE 'OUTRO CURSO'
				END AS "NOME DO CURSO"

		,CONVERT(DATE, DATA_INICIO) AS "DATA INICIO",	
						CASE YEAR(DATA_INICIO)						
							WHEN 2019 THEN 'ANO ANTERIOR'			
							WHEN 2020 THEN 'ANO ATUAL'				
							WHEN 2021 THEN 'PROXIMO ANO'			
						ELSE 'ANO INVALIDO'							
						END AS "ANALISE DE ANO"			
FROM TTEMP;		
-------------------------------------------------------------------------------------------------------------------------------------------------


--TESTANDO QUERY 2
SELECT X.*
FROM(
			SELECT NOME,
					CASE SEXO
						WHEN 'F' THEN 'FEMININO'
						WHEN 'M' THEN 'MASCULINO'
					ELSE 'VERIFIQUE'
					END AS "SEXO DO ALUNO",

							CASE NOME_CURSO
								WHEN 'WORD AVANÇADO' THEN 'WORDZÃO'
							ELSE 'OUTRO CURSO'
							END AS "NOME DO CURSO"

					,CONVERT(DATE, DATA_INICIO) AS "DATA INICIO",	
									CASE YEAR(DATA_INICIO)						
										WHEN 2019 THEN 'ANO ANTERIOR'			
										WHEN 2020 THEN 'ANO ATUAL'				
										WHEN 2021 THEN 'PROXIMO ANO'			
									ELSE 'ANO INVALIDO'							
									END AS "ANALISE DE ANO"			
			FROM TTEMP	
     )X	
WHERE [SEXO DO ALUNO] = 'VERIFIQUE' 
-------------------------------------------------------------------------------------------------------------------------------------------------

--IDENTIFICANDO E ANALISANDO IDADE DOS ALUNOS

SELECT NOME		
	  ,DATA_NASCIMENTO	
	  ,DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) IDADE,
	  CASE
		 WHEN DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) < 18 THEN 'MENOR DE IDADE'
		 WHEN DATEDIFF(YEAR, DATA_NASCIMENTO, GETDATE()) >=18 THEN 'MAIOR DE IDADE'
	 END "STATUS DA IDADE'"
FROM ALUNOS
ORDER BY IDADE ASC
-------------------------------------------------------------------------------------------------------------------------------------------------

