--PROCEDURES

--CONJUNTOS DE COMANDOS SQLs QUE PODEM SER EXECUTADOS DE UMA SÓ VEZ
------------------------------------------------------------------------------------------------------------------------


--BUSCAR INFORMAÇÕES COM PROCEDURES

CREATE PROCEDURE BUSCACURSO                         --CREANDO PROCEDURE CHAMADA BUSCACURSO
	@NOMECURSO VARCHAR(20)							--DECLARANDO A VARIAVEL COMO VARCHAR
AS
					
SET @NOMECURSO = '%' + @NOMECURSO + '%';			--DEFININDO QUE O QUE A VARIAVEL VAI RECEBER

SELECT C.ID_CURSO									--SELECIONE O ID DO CURSO
	  ,C.NOME_CURSO									--SELECIONE O NOME DO CURSO
	  ,A.NOME										--SELECIONE O NOME DO ALUNO
	  ,ISNULL(A.SEXO, 'NI') SEXO					--SELECIONE O SEXO DO ALUNO, CASO FOR NULL, MUDE PARA NI
FROM CURSOS C										--DA TABELA CURSOS
	 INNER JOIN TURMAS T							--FAÇA UM INNER JOIN ENTRE A TABELA TURMAS
		ON (T.ID_CURSO = C.ID_CURSO)				
		INNER JOIN ALUNOSXTURMAS ALT				--INNER JOIN ENTRE A TABELA ALUNOSXTURMAS
			ON (ALT.ID_ALUNO = ALT.ID_ALUNO)			
				INNER JOIN ALUNOS A					--INNER JOIN ENTRE A TABELA ALUNOS
					ON (A.ID_ALUNO = ALT.ID_ALUNO)
WHERE NOME_CURSO LIKE @NOMECURSO					--MOSTRE TUDO ISSO QUANDO O NOME DO CURSO SEJA A VARIAVEL

EXEC BUSCACURSO 'VBA';								--EXECUTANDO A PROCEDURES, BASTA APENAS TROCAR O VALOR DA VARIAVEL EM
													--EM VEZ DE FAZER A QUERY INTERIA NOVAMENTE.
--------------------------------------------------------------------------------------------------------------------------

--INSERIR INFORMAÇÕES COM PROCEDURES DENTRO DE UMA TABELA

CREATE PROCEDURE INCLUIRNOVOCURSO							  --CREATE PROCEDURE INCLUIRNOVOCURSO
	@NOMECURSO VARCHAR(100),								  --DECLARANDO A VARIAVEL NOMECURSO	
	@LOGINCADASTRO VARCHAR(100)								  --DECLARANDO A VARIAVEL LOGINCADASTRO
															  --LEMBRANDO QUE AS VARIAVEIS ANTES DO AS, VAI SER AS VARIAVEIS DE ENTRADA
AS															  --FAÇA
BEGIN														  --BEGIN PARA COMEÇAR UM QUERY
	DECLARE @IDCURSO INT;									  --DECLARE A VARIAVEL DE CONTROLE DA QUERY		
			
	SELECT @IDCURSO = MAX(ID_CURSO) + 1						  --FAÇA COM QUE A VARIAVEL DE CONTROLE SEJA O ULTIMO ID_CURSO DA TABELA CURSO + 1, 
															  --CASO NÃO SAIBA QUAL É O ULTIMO ID DA TABELA ESPECIFICA
	FROM CURSOS;											  --TABELA CURSOS

	INSERT INTO CURSOS										  --FAÇA UMA INSERÇÃO NA TABELA CURSOS
		(id_curso, nome_curso, data_cadastro, login_cadastro) --MOSTRANDO AS COLUNAS QUE TEM NA TABELA
	VALUES
		(@IDCURSO, @NOMECURSO, GETDATE(), @LOGINCADASTRO)	  --COLOCANDO AS VARIAVEIS NO INSERT EM VEZ DE COLOCAR AS ALTERAÇÕES MANUAIS,
															  --NESSE CASO ENTRA A VARIAVEL DE ENTRADA E AS DE CONTROLE.
	SELECT @IDCURSO = ID_CURSO								  --FAÇA COM QUE O @IDCURSO RECEBA O ID_CURSO NOVO
	FROM CURSOS												  --DA TABELA CURSO	
	WHERE ID_CURSO = @IDCURSO								  --ONDE O ID_CURSO VAI SER IGUAL A VARIAVEL IDCURSO

	SELECT @IDCURSO AS RETORNO;								  --RETORNE A VARIAVEL COM O NOVO IDCURSO CHAMADO RETORNO

END															  --FINALIZE 
GO

EXEC INCLUIRNOVOCURSO 'EXCEL VI' , 'RODRI11';				  --EXECUTE A PROCEDURE COLOCANDO UM NOVO CURSO

SELECT *
FROM CURSOS;

DELETE FROM Cursos WHERE ID_CURSO = 14
--------------------------------------------------------------------------------------------------------------------------

--PROCEDURES COM VALIDAÇÃO

CREATE PROCEDURE IncluiNovoCursoComValidação
		@NOMECURSO VARCHAR(100),
		@LOGINCADASTRO VARCHAR(100)

AS
BEGIN
		DECLARE @IDCURSO INT;
		DECLARE @EXISTECURSO INT;

		SELECT @EXISTECURSO = id_curso 
		FROM CURSOS 
		WHERE nome_curso = @NOMECURSO;

		IF @EXISTECURSO > 0
			BEGIN 
				SELECT 'O CURSO JÁ EXITE! GRAVAÇÃO NÃO REALIAZADA' AS "MENSAGEM DE RETORNO"
			END
		ELSE
			BEGIN
				SELECT @IDCURSO = MAX(ID_CURSO) + 1
				FROM CURSOS;

				INSERT INTO CURSOS 
					(id_curso, nome_curso, data_cadastro, login_cadastro)
				VALUES
					(@IDCURSO, @NOMECURSO, GETDATE(), @LOGINCADASTRO)

				SELECT @IDCURSO = ID_CURSO
				FROM CURSOS
				WHERE ID_CURSO = @IDCURSO

				SELECT @IDCURSO AS RETORNO
			END
END

EXEC IncluiNovoCursoComValidação 'VBA II', 'RODRI11';
--------------------------------------------------------------------------------------------------------------------------