--SEQUENCES 

--O QUE SÃO SEQUENCES
--COMO CRIA-LAS
--ALTERAR SEQUENCES
--APAGAR SEQUENCES
--RESTARTAR O CONTADOR DAS SEQUENCES

-----------------------------------------------------------------------------------------
SELECT *
FROM Alunos;

SELECT MAX(ID_ALUNO) +1
FROM Alunos;

-----------------------------------------------------------------------------------------

CREATE SEQUENCE SEQ_TESTE01; -- CRIANDO UMA SEQUENCE PADRÃO COM BIGINT

SELECT NEXT VALUE FOR SEQ_TESTE01; -- EXECUTANDO O COMANDO PARA VISUALIZAR ESSA SEQUENCE

-----------------------------------------------------------------------------------------
-- TIPOS DE INCREMENTOS
/*
TINYINT - INTERVALO DE 0 A 255;
SMALLINT - INTERVALO DE -32.768 A 32.767
INT - INTERVALO DE -2.147.483.648 A 2.147.483.647
BIGINT - INTERVALO -9.223.372.036.854.775.808 A 9.223.372.036.854.775.808 ** PADRÃO
DECIMAL E NUMERIC COM UMA ESCALA DE 0.
*/
-----------------------------------------------------------------------------------------

CREATE SEQUENCE SEQ_TESTE02 -- NOME DA SEQUENCE
	AS NUMERIC -- QUAL TIPO DE INCREMENTADOR
	START WITH 1 -- DEFININDO DA ONDE A SEQUENCE VAI COMEÇAR, NO CASO, DA PRIMEIRA POSIÇÃO
	INCREMENT BY 1; -- FATOR DE INCREMENTO DA NOSSA SEQUENCE, ADICIONAR OU RETIRAR

SELECT NEXT VALUE FOR SEQ_TESTE02; -- TODAS AS VEZES QUE VOCE APERTAR PARA EXECUTAR, ELE SEMPRE AUMENTA.

-----------------------------------------------------------------------------------------
--APAGAR UMA SEQUENCE, CASO TENHA UMA REPITIDA

DROP SEQUENCE SEQ_TESTE01;

-----------------------------------------------------------------------------------------
--SEQUENCE RETIRANDO O VALOR EM VEZ DE ADICONAR

CREATE SEQUENCE SEQ_TESTE03 -- NOME DA SEQUENCE
	START WITH 100 --POSIÇÃO QUE ELA VAI INICIAR 
	INCREMENT BY -1; --FATOR DE INCREMENTO, NO CASO, -1, ENTAO ELE VAI RETIRAR 1 SEMPRE QUE EXECUTAR

SELECT NEXT VALUE FOR SEQ_TESTE03;
-----------------------------------------------------------------------------------------

--VALORS MININOS E MAXIMOS

CREATE SEQUENCE SEQ_TESTE04 --NOME DA SEQUENCE
	START WITH 1 --POSIÇÃO PARA INICIAR
	INCREMENT BY 1 --ADICIONAR SEMPRE 1
	MINVALUE 1 --TEM QUE TER NO MININO 1 POSIÇÃO
	MAXVALUE 1000 --TEM QUE TER NO MAXIMO 1000 POSIÇÕES

SELECT NEXT VALUE FOR SEQ_TESTE04;
-----------------------------------------------------------------------------------------

--VALORES MININOS E MAXIMOS COM CYCLE, DEFINIR SE A SEQUENCE VAI SER REUTILIZADA APÓS BATER O VALOR MAXIMO

CREATE SEQUENCE SEQ_TESTE05 --NOME DA SEQUENCE
	START WITH 1 --POSIÇÃO PARA INICIAR
	INCREMENT BY 1 --ADICIONAR SEMPRE 1
	MINVALUE 1 --TEM QUE TER NO MININO 1 POSIÇÃO
	MAXVALUE 1000 --TEM QUE TER NO MAXIMO 1000 POSIÇÕES
	CYCLE; --SEQUENCE VAI VOLTAR PARA A POSIÇÃO 1 APÓS BATER O VALOR MAXIMO

SELECT NEXT VALUE FOR SEQ_TESTE05;
-----------------------------------------------------------------------------------------

--CACHE
CREATE SEQUENCE SEQ_TESTE06 --NOME DA SEQUENCE
	START WITH 1 --POSIÇÃO PARA INICIAR
	INCREMENT BY 1 --ADICIONAR SEMPRE 1
	MINVALUE 1 --TEM QUE TER NO MININO 1 POSIÇÃO
	MAXVALUE 1000 --TEM QUE TER NO MAXIMO 1000 POSIÇÕES
	CYCLE --SEQUENCE VAI VOLTAR PARA A POSIÇÃO 1 APÓS BATER O VALOR MAXIMO
	CACHE 3; --DEIXA SALVO NA SEQUENCE OS 3 VALORES POR EXEMPLO, AGILIZANDO AINDA MAIS

SELECT NEXT VALUE FOR SEQ_TESTE06;
-----------------------------------------------------------------------------------------

--ALTERAR UMA SEQUENCE 

ALTER SEQUENCE SEQ_TESTE05 --DEFINIR QUAL SEQUENCE VAI SER ALTERADO
	RESTART WITH 100 --ALTERANDO DE QUAL POSIÇÃO A SEQUENCE VAI COMEÇAR
	MAXVALUE 10000 --ALTERANDO O VALOR MAXIMO QUE A SEQUENCE PODE TER
	NO CACHE; --DEFININDO QUE A SEQUENCE NÃO VAI TER CACHE, POIS NO PADRÃO ELE JA VEM DEFINIDO COM

SELECT NEXT VALUE FOR SEQ_TESTE05;
-----------------------------------------------------------------------------------------

--CONSULTAR UMA SEQUENCE

SELECT *
FROM SYS.SEQUENCES 
WHERE NAME = 'SEQ_TESTE05';

SELECT *
FROM SYS.SEQUENCES 
WHERE NAME = 'SEQ_TESTE02';
-----------------------------------------------------------------------------------------

--CONSULTAR O ULTIMO VALOR DA SEQUENCE

SELECT LAST_USED_VALUE
FROM SYS.SEQUENCES 
WHERE NAME = 'SEQ_TESTE03';

SELECT LAST_USED_VALUE
FROM SYS.SEQUENCES 
WHERE NAME = 'SEQ_TESTE04';
-----------------------------------------------------------------------------------------

--SELECIONAR TODAS AS SEQUENCES CRIADAS

SELECT *
FROM SYS.SEQUENCES;