--UPDATE


--ALTERAÇÃO DOS DADOS ARMAZENADOS EM UMA TABELA
------------------------------------------------------------------------------------------


SELECT *
INTO TEMP --CRIANDO UMA TABELA COM O NOME TEMP 
FROM ALUNOS; --UTILIZANDO TODAS AS INFORMAÇÕES DA TABELA ALUNOS.

SELECT *
FROM TEMP; --VERIFICANDO SE A TABELA FOI CRIADA.

UPDATE TEMP --ATUALIZANDO AS INFORMAÇÕES DA TABELA TEMP
	SET SEXO = 'M'; --MODIFICANDO TODAS AS INFORMAÇÕES DA COLUNA SEXO PARA 'M'

SELECT *
FROM TEMP; --VERIFICANDO PARA VER SE DEU CERTO

DROP TABLE TEMP; --APAGANDO A TABELA TEMP.
------------------------------------------------------------------------------------------

SELECT *
INTO TEMP --CRIANDO UMA TABELA COM O NOME TEMP 
FROM ALUNOS; --UTILIZANDO TODAS AS INFORMAÇÕES DA TABELA ALUNOS

UPDATE TEMP --ATUALIZANDO AS INFORMÃÇÕES DA TABELA TEMP
	SET SEXO = NULL --ALTERANDO OS CAMPOS DA COLUNA SEXO PARA NULL

SELECT *
FROM TEMP; -- VERIFICANDO SE DEU CERTO.

DROP TABLE TEMP; --APAGANDO A TABELA
------------------------------------------------------------------------------------------

SELECT *
INTO TEMP --CRIANDO UMA TABELA COM O NOME TEMP
FROM ALUNOS; --UTILIZANDO TODAS AS INFORMAÇÕES DA TABELA ALUNOS PARA ISSO

SELECT * 
FROM TEMP; --VERIFICANDO SE DEU CERTO.

UPDATE TEMP	--ATUALIZANDO AS INFORMAÇÕES DA TABELA TEMP
	SET SEXO = 'F' --COLOCANDO COMO 'F' NO CAMPO DE SEXO
	WHERE ID_ALUNO BETWEEN 1 AND 4; --APENAS OS ALUNOS COM OS IDs ENTRE 1 A 4

UPDATE TEMP --ATUALIANDO A TABELA TEMP
	SET NOME = UPPER(NOME); --COLOCANDO OS NOMES DOS ALUNOS EM LETRAS MAISCULAS

SELECT *
FROM TEMP; --VERIFICANDO A TABELA SE DEU CERTO

UPDATE TEMP --ATUALIANDO A TABELA TEMP
	SET NOME = LOWER(NOME), --COLOCANDO TODOS OS NOMES EM MINUSCULA 
		SEXO = UPPER(SEXO) --E OS SEXOS EM MAIUSCULAS 
WHERE ID_ALUNO BETWEEN 1 AND 5; --APENAS DOS ALUNOS COM ID DE 1 A 5

UPDATE TEMP	--ATUALIANDO A TABELA TEMP
	SET SEXO = UPPER(SEXO), --COLOCANDO TODOS OS SEXOS EM MAIUSCULAS
		NOME = UPPER(NOME); --COLOCANDO TODOS OS NOMES EM MAIUSCULAS

SELECT *
FROM TEMP;

UPDATE TEMP	--ATUALIANDO A TABELA TEMP
	SET SEXO = 'M' --COLOCANDO O SEXO PARA M
WHERE ID_ALUNO BETWEEN 1 AND 4; --DOS ALUNOS COM ID DE 1 A 4;
	
SELECT *
FROM TEMP;

UPDATE TEMP --ATUALIANDO A TABELA TEMP
	SET SEXO = 'F' --COLOCANDO SEXO COMO 'F'
WHERE ID_ALUNO BETWEEN 7 AND 9; --DOS ALUNOS COM ID DE 7 A 9;

SELECT *
FROM TEMP;

DROP TABLE TEMP; --APAGANDO A TABELA.
